### ISSUE TITLE
Cmake配置错误的问题

### ISSUE THREAD

**Issue by 13824125580** [isrc-cas/c910-llvm#1]
您好：
　请教，我完全按照仓库中的readme.md进行操作，cmake配置的时候出问题，可否帮忙看一下，是ＳＤＫ本身的问题，还是我的工具环境配置问题，　谢谢!

czl@czl-Vostro-3268:~/WorkSpace/llvm/c910-llvm$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
czl@czl-Vostro-3268:~/WorkSpace/llvm/c910-llvm$ mkdir build
czl@czl-Vostro-3268:~/WorkSpace/llvm/c910-llvm$ cd build/
czl@czl-Vostro-3268:~/WorkSpace/llvm/c910-llvm/build$ cmake -DLLVM_TARGETS_TO_BUILD="RISCV" -DLLVM_ENABLE_PROJECTS=clang  -G "Unix Makefiles" ../llvm
**CMake Error: The source directory "/home/czl/WorkSpace/llvm/c910-llvm/llvm" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.**

谢谢！

**Comment by lazyparser** [comment]
Hi @13824125580 

非常感谢反馈bug❤️

快速确认了下，这是我们的工作没有做好：

1. 在README中，cmake命令出现了错误， `../llvm` should be `..`
2. 本仓库目前没有包含 Clang，需要从LLVM官方[1] 下载一个 clang 9.0 解压缩之后再执行 cmake。

我们将尽快修正README中缺失的部分。

再次感谢🎉 大概周一中午12点之前就可以重新尝试下了

[1] https://releases.llvm.org/9.0.0/cfe-9.0.0.src.tar.xz

**Comment by 13824125580** [comment]
谢谢您的及时协助！
















在 2020-07-13 00:27:51，"Wei Wu" <notifications@github.com> 写道：

Hi @13824125580

非常感谢反馈bug❤️

快速确认了下，这是我们的工作没有做好：

在README中，cmake命令出现了错误， ../llvm should be ..
本仓库目前没有包含 Clang，需要从LLVM官方[1] 下载一个 clang 9.0 解压缩之后再执行 cmake。

我们将尽快修正README中缺失的部分。

再次感谢 大概周一中午12点之前就可以重新尝试下了

**Comment by lazyparser** [comment]
Hi @13824125580 

目前已经更新了README，可以尝试下。

同时增加了带clang和不带clang两种编译方式。

增加了测试用例完成的结果的输出参考。

**Comment by lazyparser** [comment]
Fixed
